version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - default
    ports:
      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db

  patient:
    depends_on:
      - mysqldb
    image: patient
    container_name: patient
    build:
      context: patient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      - "spring.datasource.url=jdbc:mysql://mysqldb/mediscreen?serverTimezone=UTC"
      - "spring.datasource.username=root"
      - "spring.datasource.password=root"

  note:
    depends_on:
      - mongodb
    image: note
    container_name: note
    build:
      context: note
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - default
    environment:
      - "spring.data.mongodb.host=mongodb"

  alert:
    depends_on:
    - note
    - patient
    image: alert
    container_name: alert
    build:
      context: alert
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - default
    environment:
      - "endpoint.patientUri=http://patient:8081"
      - "endpoint.noteUri=http://note:8082"

  front:
    depends_on:
      - note
      - patient
      - alert
    image: front
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - default
    environment:
      - "endpoint.patientUri=http://patient:8081"
      - "endpoint.noteUri=http://note:8082"
      - "endpoint.alertUri=http://alert:8083"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: