version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - default
    ports:
      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

#  mongodb:
#    image: mongo:4
#    ports:
#      - "8082:8082"
#    volumes:
#      - mongodb_data:/data/db

  adminer:
    image: adminer
    container_name: mysqladmin
    restart: always
    ports:
      - "8080:8080"

  patient:
    depends_on:
      - mysqldb
    image: patient
    container_name: patient
    build:
      context: patient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      - "spring.datasource.url=jdbc:mysql://mysqldb/mediscreen?serverTimezone=UTC"
      - "spring.datasource.username=root"
      - "spring.datasource.password=root"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: