FROM openjdk:17-jdk-alpine
MAINTAINER Tsy-Yeung Lau
COPY target/patient-0.0.1-SNAPSHOT.jar patient-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/patient-0.0.1-SNAPSHOT.jar"]

# Ficher compose.yml
# Créer la BDD dans le Docker
# Créer le MongoDB dans le Docker
